### ISSUE TITLE
服务中心注册服务和服务调用问题

### ISSUE THREAD

**Issue by feelanture** [ServiceComb/ServiceComb-Java-Chassis#130]
您好：
      我使用华为运服务，按照网站指导，下载sdk和服务中心，启动服务中心，然后用maven构件例子程序，构建成功，导入eclipse工具。
      1）启动服务中心，类型为：service-center-0.1.1-windows-amd64，运行start.bat，启动服务中心，一直滚动如下信息：
2017-09-04T17:27:44.4495078+08:00 DEBUG service_center 31924 github.com/ServiceC
omb/service-center/server/core/registry/store/async_task.go collectReadyTasks():
208 - service_center."no task in queue, key is /cse-sr/inst/leases/default/defau
lt/27b96c20914811e7888a9c4e36cb7735/27e75a9c914811e7888a9c4e36cb7735"
2017-09-04T17:27:44.4495078+08:00 DEBUG service_center 31924 github.com/ServiceC
omb/service-center/server/core/registry/store/async_task.go collectReadyTasks():
208 - service_center."no task in queue, key is /cse-sr/inst/leases/default/defau
lt/3ed620f0914b11e7888a9c4e36cb7735/c69cb067914d11e7888a9c4e36cb7735"
2）启动pojo的例子程序，运行PojoProviderMain，注册服务，出现如下异常：
2017-09-04 16:48:06,468 [WARN] Thread Thread[transport-vert.x-eventloop-thread-0,5,main] has been blocked for 5485 ms, time limit is 2000 io.vertx.core.impl.BlockedThreadChecker$1.run(BlockedThreadChecker.java:57)
io.vertx.core.VertxException: Thread blocked
	at java.net.NetworkInterface.getAll(Native Method)
	at java.net.NetworkInterface.getNetworkInterfaces(Unknown Source)
	at io.netty.util.internal.MacAddressUtil.bestAvailableMac(MacAddressUtil.java:58)
	at io.netty.channel.DefaultChannelId.defaultMachineId(DefaultChannelId.java:127)
	at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:104)
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:146)
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:114)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:233)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:212)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:348)
	at io.vertx.core.impl.AddressResolver$1.newResolver(AddressResolver.java:167)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:223)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:690)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:74)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:256)
	at io.servicecomb.transport.rest.vertx.RestServerVerticle.startListen(RestServerVerticle.java:95)
	at io.servicecomb.transport.rest.vertx.RestServerVerticle.start(RestServerVerticle.java:91)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
	at io.vertx.core.impl.DeploymentManager$$Lambda$26/1595687022.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$27/1369352990.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Unknown Source)
3）启动客户端程序，运行PojoConsumerMain，出现如下异常：
2017-09-04 17:30:24,925 [WARN] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hello': Invocation of init method failed; nested exception is io.servicecomb.foundation.common.exceptions.ServiceCombException: microserviceName=hello, schemaid=hello, 
do not support implicit interface anymore, 
because that caused problems:
  1.the startup process relies on other microservices
  2.cyclic dependent microservices can not be deployed
suggest to use @RpcReference or <cse:rpc-reference id="..." microservice-name="..." schema-id="..." interface="..."></cse:rpc-reference>. org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'hello': Invocation of init method failed; nested exception is io.servicecomb.foundation.common.exceptions.ServiceCombException: microserviceName=hello, schemaid=hello, 
do not support implicit interface anymore, 
because that caused problems:
  1.the startup process relies on other microservices
  2.cyclic dependent microservices can not be deployed
suggest to use @RpcReference or <cse:rpc-reference id="..." microservice-name="..." schema-id="..." interface="..."></cse:rpc-reference>.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:235)
	at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:702)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:527)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at io.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:36)
	at io.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:32)
	at io.servicecomb.samples.pojo.consumer.PojoConsumerMain.init(PojoConsumerMain.java:49)
	at io.servicecomb.samples.pojo.consumer.PojoConsumerMain.main(PojoConsumerMain.java:38)
Caused by: io.servicecomb.foundation.common.exceptions.ServiceCombException: microserviceName=hello, schemaid=hello, 
do not support implicit interface anymore, 
because that caused problems:
  1.the startup process relies on other microservices
  2.cyclic dependent microservices can not be deployed
suggest to use @RpcReference or <cse:rpc-reference id="..." microservice-name="..." schema-id="..." interface="..."></cse:rpc-reference>.
	at io.servicecomb.provider.pojo.reference.PojoReferenceMeta.afterPropertiesSet(PojoReferenceMeta.java:75)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1642)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1579)
	... 15 more

请问是什么原因造成此现象，谢谢！

**Comment by jeho0815** [comment]
1、我们现在提供的是64位的ServiceCenter，请检查下，如果还是有问题，能不能提供比较详细的日志信息。
2、请先确保服务中心启动ok，然后查看服务的注册中心地址配置是否正确，如果都没有问题，请提供你运行环境信息，方便排查
3、需要服务端注册上了，客户端才能调用到服务端

**Comment by bismy** [comment]
问题3: 需要修改pojo.consumer.bean.xml。 
	<cse:rpc-reference id="hello" microservice-name="hello"
		schema-id="hello" interface="io.servicecomb.samples.common.schema.Hello"></cse:rpc-reference>

最近的代码优化，examples忘记合入。这个需要提交一个issue解决。

**Comment by bismy** [comment]
问题2： 很可能和本机HOSTS或者DNS设置有关系。需要结合前面的日志，看看监听的IP地址是否选择正确。或者将监听IP地址由0.0.0.0显示的修改为127.0.0.1或者本机的其他IP地址试试。

**Comment by feelanture** [comment]
谢谢，已经解决！
