### ISSUE TITLE
BMI Loadbalance Sample do not work properly

### ISSUE THREAD

**Issue by zhuhoudong** [ServiceComb/ServiceComb-Java-Chassis#149]
I followed below, and error occured when registrying the webapp to Service-Center.

BTW, it works in No loadbalance mode.  
service-center-0.1.1-windows-amd64,  and I run start.bat  in windows.

<img width="583" alt="2017-09-18_161852" src="https://user-images.githubusercontent.com/31299631/30533659-19bb9ea6-9c8d-11e7-96ea-3f3f6a32a493.png">

Error:

2017-09-18 16:22:13,899 [WARN] service center has no available instance io.servicecomb.serviceregistry.client.IpPortManager.nextDefaultIpPort(IpPortManager.java:139)
2017-09-18 16:22:13,900 [ERROR] Registry microservice failed. appId=bmi, name=gateway, version=0.0.1 io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:77)
2017-09-18 16:22:13,900 [INFO] read MicroserviceRegisterTask status is READY io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)
2017-09-18 16:23:13,901 [INFO] running microservice register task. io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:57)
2017-09-18 16:23:13,904 [ERROR] GET /registry/v3/existence?appId=bmi&type=microservice&serviceName=gateway&version=0.0.1 fail, endpoint is 127.0.0.1:30100, message: Failed to create SSL connection io.servicecomb.serviceregistry.client.http.RestUtils.lambda$null$1(RestUtils.java:80)
2017-09-18 16:23:13,905 [WARN] service center has no available instance io.servicecomb.serviceregistry.client.IpPortManager.nextDefaultIpPort(IpPortManager.java:139)
2017-09-18 16:23:13,909 [ERROR] POST /registry/v3/microservices fail, endpoint is 127.0.0.1:30100, message: Failed to create SSL connection io.servicecomb.serviceregistry.client.http.RestUtils.lambda$null$1(RestUtils.java:80)
2017-09-18 16:23:13,910 [WARN] service center has no available instance io.servicecomb.serviceregistry.client.IpPortManager.nextDefaultIpPort(IpPortManager.java:139)
2017-09-18 16:23:13,912 [ERROR] Registry microservice failed. appId=bmi, name=gateway, version=0.0.1 io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:77)

**Comment by WillemJiang** [comment]
Can you check if the service center is started at the 127.0.0.1:30100?

**Comment by zhuhoudong** [comment]
@WillemJiang 

The log shows that "service_center."listen on server 127.0.0.1:30100." "

BTW, why there are so many debug logs "service-center-0.1.1-windows-amd64" console, can I ture it off? 

2017-09-19T08:54:46.4809011+08:00 INFO service_center 13372 github.com/ServiceComb/service-center/server/api/api_server.go registryInstance():190 - service_center."register service center instance successfully, instance 527ad4119c4811e7911c9883892405ac/21a7c16f9cd511e799a89883892405ac, endpoints [rest://127.0.0.1:30100]"
2017-09-19T08:54:46.4809011+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/service/dependency/dependency_service.go GetConsumersInCache():95 - service_center."query service consumers in cache 527ad4119c4811e7911c9883892405ac"
2017-09-19T08:54:46.4819055+08:00 INFO service_center 13372 github.com/ServiceComb/service-center/server/api/api_server.go Start():263 - service_center."api server is ready"
2017-09-19T08:54:46.4819055+08:00 WARN service_center 13372 github.com/ServiceComb/service-center/util/rest/server.go ListenAndServe():73 - service_center."listen on server 127.0.0.1:30100."
2017-09-19T08:54:47.3873481+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:54:48.3889788+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:54:55.786892+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:54:56.7875401+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:54:57.7882569+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:55:08.8945515+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"
2017-09-19T08:55:09.8951723+08:00 DEBUG service_center 13372 github.com/ServiceComb/service-center/server/core/registry/store/async_task.go schedule():143 - service_center."timed out to collect ready tasks"

**Comment by WillemJiang** [comment]
Can you check if the firewall block the service-center?

**Comment by zhuhoudong** [comment]
I think Service-Center  is OK。 Because the following samples  works。
Service Management
Flow Control

Correction:  Registry error  is not from  calculator , but from webapp.

**Comment by WillemJiang** [comment]
It's strange,  can you restart the webapp?

**Comment by zhuhoudong** [comment]
Same error when I restart the webapp。 （both webapp and service center are started from windows，not VM or docker）

2017-09-19 16:09:55,476 [ERROR] can not get microservice id, bmi:calculator:latest io.servicecomb.core.definition.schema.ConsumerSchemaFactory.findMicroservice(ConsumerSchemaFactory.java:94)
2017-09-19 16:09:55,478 [WARN] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonServerList' defined in ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ServerList]: Factory method 'ribbonServerList' threw exception; nested exception is java.lang.IllegalStateException: Probably invoke a service before it is registered, appId=bmi, name=calculator org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
2017-09-19 16:09:55,484 [WARN] Error during filtering org.springframework.cloud.netflix.zuul.filters.post.SendErrorFilter.run(SendErrorFilter.java:70)
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ribbonServerList' defined in ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ServerList]: Factory method 'ribbonServerList' threw exception; nested exception is java.lang.IllegalStateException: Probably invoke a service before it is registered, appId=bmi, name=calculator
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1128) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1022) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:512) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:754) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:110) ~[spring-cloud-context-1.1.8.RELEASE.jar:1.1.8.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:79) ~[spring-cloud-context-1.1.8.RELEASE.jar:1.1.8.RELEASE]
        at org.springframework.cloud.context.named.NamedContextFactory.getInstance(NamedContextFactory.java:115) ~[spring-cloud-context-1.1.8.RELEASE.jar:1.1.8.RELEASE]
        at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getInstance(SpringClientFactory.java:111) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.ribbon.SpringClientFactory.getClient(SpringClientFactory.java:49) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.apache.HttpClientRibbonCommandFactory.create(HttpClientRibbonCommandFactory.java:54) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.apache.HttpClientRibbonCommandFactory.create(HttpClientRibbonCommandFactory.java:33) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.forward(RibbonRoutingFilter.java:137) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.cloud.netflix.zuul.filters.route.RibbonRoutingFilter.run(RibbonRoutingFilter.java:88) ~[spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at com.netflix.zuul.ZuulFilter.runFilter(ZuulFilter.java:112) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.FilterProcessor.processZuulFilter(FilterProcessor.java:193) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.FilterProcessor.runFilters(FilterProcessor.java:157) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.FilterProcessor.route(FilterProcessor.java:118) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.ZuulRunner.route(ZuulRunner.java:96) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.http.ZuulServlet.route(ZuulServlet.java:116) [zuul-core-1.3.0.jar:1.3.0]
        at com.netflix.zuul.http.ZuulServlet.service(ZuulServlet.java:81) [zuul-core-1.3.0.jar:1.3.0]
        at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:157) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.cloud.netflix.zuul.web.ZuulController.handleRequest(ZuulController.java:44) [spring-cloud-netflix-core-1.2.6.RELEASE.jar:1.2.6.RELEASE]
        at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55) [spring-boot-1.4.5.RELEASE.jar:1.4.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105) [spring-boot-actuator-1.4.5.RELEASE.jar:1.4.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106) [spring-boot-actuator-1.4.5.RELEASE.jar:1.4.5.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.11.jar:8.5.11]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.loadbalancer.ServerList]: Factory method 'ribbonServerList' threw exception; nested exception is java.lang.IllegalStateException: Probably invoke a service before it is registered, appId=bmi, name=calculator
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        ... 86 more
Caused by: java.lang.IllegalStateException: Probably invoke a service before it is registered, appId=bmi, name=calculator
        at io.servicecomb.core.definition.schema.ConsumerSchemaFactory.getOrCreateMicroserviceMeta(ConsumerSchemaFactory.java:73) ~[java-chassis-core-0.3.0-SNAPSHOT.jar:?]
        at io.servicecomb.core.provider.consumer.ReferenceConfig.<init>(ReferenceConfig.java:35) ~[java-chassis-core-0.3.0-SNAPSHOT.jar:?]
        at io.servicecomb.core.provider.consumer.ConsumerProviderManager.getReferenceConfig(ConsumerProviderManager.java:74) ~[java-chassis-core-0.3.0-SNAPSHOT.jar:?]
        at io.servicecomb.springboot.starter.discovery.CseRoutesProperties.getVersionRule(CseRoutesProperties.java:34) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at io.servicecomb.springboot.starter.discovery.ServiceCombServerList.initWithNiwsConfig(ServiceCombServerList.java:76) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration.ribbonServerList(CseRibbonClientConfiguration.java:47) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration$$EnhancerBySpringCGLIB$$ac958715.CGLIB$ribbonServerList$0(<generated>) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration$$EnhancerBySpringCGLIB$$ac958715$$FastClassBySpringCGLIB$$924456.invoke(<generated>) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356) ~[spring-context-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at ribbon.io.servicecomb.springboot.starter.discovery.CseRibbonClientConfiguration$$EnhancerBySpringCGLIB$$ac958715.ribbonServerList(<generated>) ~[spring-boot-starter-discovery-0.3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.4.RELEASE.jar:4.3.4.RELEASE]
        ... 86 more
2017-09-19 16:09:58,116 [WARN] sc task interval changed from 10 to 20 io.servicecomb.serviceregistry.task.ServiceCenterTaskMonitor.beginCycle(ServiceCenterTaskMonitor.java:38)
2017-09-19 16:09:58,116 [INFO] running microservice register task. io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:57)
2017-09-19 16:09:58,121 [ERROR] GET /registry/v3/existence?appId=bmi&type=microservice&serviceName=gateway&version=0.0.1 fail, endpoint is 127.0.0.1:30100, message: Failed to create SSL connection io.servicecomb.serviceregistry.client.http.RestUtils.lambda$null$1(RestUtils.java:80)
2017-09-19 16:09:58,122 [WARN] service center has no available instance io.servicecomb.serviceregistry.client.IpPortManager.nextDefaultIpPort(IpPortManager.java:139)
2017-09-19 16:09:58,133 [ERROR] POST /registry/v3/microservices fail, endpoint is 127.0.0.1:30100, message: Failed to create SSL connection io.servicecomb.serviceregistry.client.http.RestUtils.lambda$null$1(RestUtils.java:80)
2017-09-19 16:09:58,134 [WARN] service center has no available instance io.servicecomb.serviceregistry.client.IpPortManager.nextDefaultIpPort(IpPortManager.java:139)
2017-09-19 16:09:58,134 [ERROR] Registry microservice failed. appId=bmi, name=gateway, version=0.0.1 io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:77)
2017-09-19 16:09:58,139 [INFO] read MicroserviceRegisterTask status is READY io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)

error in web:

<img width="702" alt="bbbb" src="https://user-images.githubusercontent.com/31299631/30582087-0780560a-9d55-11e7-9865-15f65228350a.png">

webapp 's  microservice.yaml 

<img width="337" alt="ccccc" src="https://user-images.githubusercontent.com/31299631/30582231-8bb1f406-9d55-11e7-800c-9ba02f77a69f.png">

webapp 's  application.yaml 

<img width="420" alt="eeeee" src="https://user-images.githubusercontent.com/31299631/30582357-f8d279ac-9d55-11e7-8582-7abf3df3307b.png">


service center folder:(start from start.bat)

<img width="535" alt="dddddd" src="https://user-images.githubusercontent.com/31299631/30582289-c1608338-9d55-11e7-809f-65a61dc574e5.png">

**Comment by WillemJiang** [comment]
Can you remove the below lines from  webapp 's microservice.yaml.
cse:
  handler:
     chain:
        Consumer:
            default: loadbalance
you don't need to setup the loadbalance handler for the WebApp which is Zuul Application.

**Comment by zhuhoudong** [comment]
@WillemJiang Thanks。 It goes OK 。
The following  guide (红框部分) on servicecomb web page is not correct and would you please delete  it？

![faststoneeditor](https://user-images.githubusercontent.com/31299631/30676550-3b71f922-9eb9-11e7-8b01-13a7d92529fb.png)

**Comment by WillemJiang** [comment]
@eric-lee-ltk  Can you take a look at it?

**Comment by eric-lee-ltk** [comment]
@zhuhoudong thanks for pointing out the mistakes in our guide. Can you submit a PR for this mistake? BTW, the jvmArguments is wrong in the below command and can remove from the command as the handler chain has no effect on zuul application.

**Comment by zhuhoudong** [comment]
I have submit 2 PRs (english and chinese), Please merge it, thanks!

Update load-balance.md
#98 opened a minute ago by zhuhoudong  
Update load-balance.md
#97 opened 2 minutes ago by zhuhoudong

**Comment by zhuhoudong** [comment]
Modified mistakes in guide, issue complete!
